# Example Chinese Git CI/CD Configuration

stages:
  - test
  - build

test:
  stage: test
  image: php:8.3
  script:
    - composer install
    - npm ci
    - php artisan test
  only:
    - main

build:
  stage: build
  image: node:20
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
